### ISSUE TITLE
Make map look nice

### ISSUE THREAD

**Issue by wuhland** [osmlab/basket#12]
It would be nice if the map expanded to the 100% screen width. Not clear to me if this is possible with how github renders leaflet.

**Comment by wuhland** [comment]
Maybe this is the way? https://github.com/Leaflet/Leaflet.fullscreen

**Comment by wuhland** [comment]
Also need to be able to click the marker to link back to the basket article

**Comment by danbjoseph** [comment]
- popup could still be improved
  - maybe add the post image teaser (if it has one)
  - maybe some formatting
- custom map markers?

**Comment by wuhland** [comment]
map markers change color by author now. I added MakiMarkers so we could take from one of those markers if we want. https://www.mapbox.com/maki/

**Comment by d3netxer** [comment]
The map looks awesome!

**Comment by wuhland** [comment]
Yea it does. Dan really cleaned it up. I didn't even know you could add
leaflet to a github pages site. I guess since the lat, long is coming
straight from the posts yaml we can get rid of map.geojson ya?

**Comment by d3netxer** [comment]
yes, it could be gotten rid of. However, it may have use as part of the basket API.
