### ISSUE TITLE
The page isn't redirecting properly

### ISSUE THREAD

**Issue by d3netxer** [osmlab/basket#24]
Anybody else getting problems sometimes with a page not appearing on the site due to a redirection problem? Or is it just me? @wuhland

**Comment by wuhland** [comment]
That's happened to me once so I thought it was an anomaly but if your
seeing it as well... It's likely to do with how I set up records (CNAME,
etc) with the DN provider (namecheap). Seemed pretty straight forward so
not sure where I went wrong. Anyways, should be an easy fix but could use
some consultation from somebody with experience in the matter. Any
volunteers?

**Comment by wuhland** [comment]
Actually, let me just talk to namecheap to see if I can get it worked out
before I get anyone spun up.

**Comment by d3netxer** [comment]
Ok. I don't see any issue with the CNAME. In the osmgeoweek site, the CNAME is osmgeoweek.org

which is very similar to the CNAME for basket, which is osmstories.org

**Comment by wuhland** [comment]
Yea, no I mean the resource records registered on the DN provider side, I
have both a CNAME and A record.

**Comment by d3netxer** [comment]
@wuhland fixed it!
