### ISSUE TITLE
contributor account settings

### ISSUE THREAD

**Issue by danbjoseph** [osmlab/basket#28]
@d3netxer you've got some settings out of whack
<img width="360" alt="screen shot 2016-04-20 at 7 57 10 pm" src="https://cloud.githubusercontent.com/assets/4806884/14693978/3ce08546-0732-11e6-8c18-9d982829e9da.png">
versus 
<img width="269" alt="screen shot 2016-04-20 at 7 58 47 pm" src="https://cloud.githubusercontent.com/assets/4806884/14693986/56576d46-0732-11e6-9d3c-3275c57c27b1.png">

**Comment by d3netxer** [comment]
thanks @danbjoseph , I added that e-mail to my account setting now!
