### ISSUE TITLE
Map Page

### ISSUE THREAD

**Issue by wuhland** [osmlab/basket#5]
We should make a map which displays the location of articles which have a location in their yaml. We are already creating a json search index for search, shouldn't be too hard to also export a geojson.

**Comment by wuhland** [comment]
so I mostly got it. right now I have templated out the creation of geojson for posts with coor:[lat, long] set in their yaml. problem is the result gets crammed into _site which is .gitignored and not pushed to here. We need the geojson on github tol generate a map. I could change .gitignore and push the processed _site but that seems lame. The map is rendering now but only because I manually moved copied the rendered geojson out of  _site. Anybody know if there is a way to get our geojson rendered someplace other than _site? I asked this question **poorly** here: http://stackoverflow.com/questions/31016930/can-jekyll-process-a-markdown-file-and-save-it-somewhere-besides-directory

**Comment by d3netxer** [comment]
I don't know if Jekyll can do this, but this type of functionality seems in line with stuff Grunt handles, which is already in the repo. It seems like repacking a single copy and paste with a Grunt command is not worth the effort, but it is something to consider if more tasks like this emerge.

**Comment by wuhland** [comment]
will grunt tasks run on github without being enacted by cli? In a perfect
world the map would be updated even if somebody adds a new post from
github.

On Wed, Jun 24, 2015 at 1:08 AM, @tomgertin notifications@github.com
wrote:

> I don't know if Jekyll can do this, but this type of functionality seems
> in line with stuff Grunt handles, which is already in the repo. It seems
> like repacking a single copy and paste with a Grunt command is not worth
> the effort, but it is something to consider if more tasks like this emerge.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osmlab/basket/issues/5#issuecomment-114728849.

## 

David Saeger
202-802-6382

**Comment by wuhland** [comment]
Got it working. In the end I gave up and just pushed _site. Dont think its the worst thing in the world althugh there may be a cleaner solution.
