### ISSUE TITLE
Tags Question (where are they stored)

### ISSUE THREAD

**Issue by vknoppkewetzel** [osmlab/basket#7]
Anyone know where all the tags are getting stored once someone adds them to a new post? (which file do the tags get added to/stored in? if such a file exists? html? .txt? .js? ) Or are they stored per article only? 
Such as #2015 #OSM #world #Nepal etc

Trying to find that file, if such a file exists, to see if I can play around with .scss for color coding/color ranging them

**Comment by d3netxer** [comment]
@vknoppkewetzel as it is implemented right now, the tags are originally in the front matter of the articles in the posts folder. For example this line 'tags: [HOTOSM, Case Study, GIS, Haiti, 2015]' here [2015-04-18-Haiti-HOT.md](https://raw.githubusercontent.com/osmlab/basket/gh-pages/_posts/articles/2015-04-18-Haiti-HOT.md)

When generating the Search page, Jekyll processes the posts using the i[ndex.md](https://github.com/osmlab/basket/blob/gh-pages/search/index.md) file in the search folder.

Take a look at this file and see what it is doing starting around line 25. It processes each post in a loop and converts different elements to html including the tags. It gives each tag a class="entry-tags" as well.

so you will have to mess around with the search index page and/or the css. I think we are using SASS for the css, which I haven't used before.

**Comment by vknoppkewetzel** [comment]
Okay thanks! I did see that they individually had the tags stored per case study, but definitely was hoping that maybe they also were getting stored together/appended in one space somewhere else as well. Will play around with the scss and other files and see what I can do haha. I also am new to SASS, so we will see if I actually can do anything.
