### ISSUE TITLE
tag number count

### ISSUE THREAD

**Issue by d3netxer** [osmlab/basket#9]
Right now it is not counting the number of articles tagged with either 2014 or 2015. Is this done on purpose? 

This could probably be fixed easily by removing the {% unless forloop.last %} tag on the tag index page I think.

**Comment by wuhland** [comment]
ya good catch. You think? But if the issue is {% unless forloop.last %} wouldn't it be producing mischief on just one of the two tags (2015 I suppose)

**Comment by d3netxer** [comment]
yeah your right, deleting the {% unless forloop.last %} doesn't fix anything. I put quotes around the years in the posts and that fixed the problem. 

I'm not sure how to fix the issue in the code. I couldn't find a liquid filter to convert dates or numbers into strings.

**Comment by wuhland** [comment]
I see what you mean. I thought about it for a bit and think the problem
lies in how jekyll compiles "site.tags" :

{"Ebola"=>[<Post: /articles/Ebola-GIS>], "Guinea"=>[<Post:
/articles/Ebola-GIS>], "MSF"=>[<Post: /articles/Ebola-GIS>], "Case
Study"=>[<Post: /articles/Haiti-HOT>, <Post: /articles/Botswana>, <Post:
/articles/Ebola-GIS>], "GIS"=>[<Post: /articles/Haiti-HOT>, <Post:
/articles/Ebola-GIS>], 2014=>[<Post: /articles/Ebola-GIS>],
"Botswana"=>[<Post: /articles/Botswana>], "QGIS"=>[<Post:
/articles/Botswana>], "Health"=>[<Post: /articles/Botswana>],
"Malaria"=>[<Post: /articles/Botswana>], "Peace Corps"=>[<Post:
/articles/Botswana>], 2015=>[<Post: /articles/Etalab>, <Post:
/articles/Botswana>], "France"=>[<Post: /articles/Etalab>],
"Etalab"=>[<Post: /articles/Etalab>], "Open Data"=>[<Post:
/articles/Etalab>], "indonesia"=>[<Post: /articles/Indonesia>],
"Karangetang"=>[<Post: /articles/Indonesia>], "volcano"=>[<Post:
/articles/Indonesia>], "GMU"=>[<Post: /articles/Indonesia>],
"2015"=>[<Post: /articles/Haiti-HOT>, <Post: /articles/Indonesia>],
"HOTOSM"=>[<Post: /articles/Haiti-HOT>], "Haiti"=>[<Post:
/articles/Haiti-HOT>]}

you can see that it creates an array of objects with mappings written
exactly as you write them. Maybe we could write a little liquid deduping
thing that combines all the tags that are meant to be grouped. This would
also help ensure that we dont have seperate tags set up when folks
inevitably vary  in case usage for the same tag. Didnt get far enough to
start implementing

On Sun, Jul 12, 2015 at 6:45 PM, @tomgertin notifications@github.com
wrote:

> yeah your right, deleting the {% unless forloop.last %} doesn't fix
> anything. I put quotes around the years in the posts and that fixed the
> problem.
> 
> I'm not sure how to fix the issue in the code. I couldn't find a liquid
> filter to convert dates or numbers into strings.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/osmlab/basket/issues/9#issuecomment-120770711.

## 

David Saeger
202-802-6382

**Comment by d3netxer** [comment]
Interesting. Yeah, you can use liquid filters to make all the tags strings and lower case regardless of how they start off; then the existing code would be able to group them.

This line will probably have to be replaced some how:

<span>{{ site.tags[this_word].size }}</span>

It is matching to the original tags found in the YAML to get the size. Which wouldn't work anymore after the liquid filters.

I won't be working on this site this week, maybe next week.

**Comment by d3netxer** [comment]
I recommend if we really want to automate this at some point, we make a rake task to make all the tags lower case and make the years/numbers into strings. Until then, I'll close this out.
